# Auto-generated by stubgen.py on Fri Mar 30 06:53:13 2018
# -- HAND EDITING NOT ADVISED ---


import InsTask

# Special module-level constant to tell task manager what default subsystem
# these tasks are for
SUBSYS = 'PFS'



####################################################################
# BASE PFS TASKS
####################################################################
#
class PFSTaskError(InsTask.Ins2TaskError):
    pass

class PFSTask(InsTask.Ins2Task):
    """Base PFS task from which PFS device dependent commands tasks
    are derived.
    """
    def __init__(self, cmdname, **kwdargs):
        """_cmdname_ is the command name for this task.
        """

        # This copies all keyword arguments to self.params and does
        # general task initialization
        super(PFSTask, self).__init__('PFS', cmdname, **kwdargs)

    #######################################
    # PFS INSTRUMENT COMMANDS
    #######################################


class Fits_File(PFSTask):
    def __init__(self, motor=None, frame_no=None, template=None, delay=None):
        super(Fits_File, self).__init__('Fits_File', motor=motor, frame_no=frame_no, template=template, delay=delay)

class Mcsexpose(PFSTask):
    def __init__(self, exptime=None, exptype=None):
        super(Mcsexpose, self).__init__('Mcsexpose', exptime=exptime, exptype=exptype)

class Obcp_Mode(PFSTask):
    def __init__(self, motor=None, mode=None):
        super(Obcp_Mode, self).__init__('Obcp_Mode', motor=motor, mode=mode)

class Pfscmd(PFSTask):
    def __init__(self, actor=None, cmd=None):
        super(Pfscmd, self).__init__('Pfscmd', actor=actor, cmd=cmd)

class Reload(PFSTask):
    def __init__(self, module=None):
        super(Reload, self).__init__('Reload', module=module)

class Sleep(PFSTask):
    def __init__(self, sleep_time=None):
        super(Sleep, self).__init__('Sleep', sleep_time=sleep_time)

